# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'BeTime' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'PinLayout'
  pod 'Alamofire'
  pod 'FlexLayout'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'Swinject'
  # Pods for BeTime

end
